[package]
name = "rustgpuemu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emu_core = {version="0.1", features=["glsl-compile"]}
spirv-builder = { path="./rust-gpu/crates/spirv-builder/" }